# Generated by Django 3.1.6 on 2021-02-06 14:08
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210206_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expired_pay',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
